runtime: nodejs20
env_variables:
  DATABASE_URL_LOCAL: "mysql://root:12345678@34.128.67.12:3306/asco"
  HOST: 0.0.0.0
  JWT_SECRET: "^[Nk&S,!;5;N9sUFt#,GBlsWdKB,YPaMyTY]zv4SCkNd}aioJ#"
  ISSUER: api.jj
  GCP_PUB_SUB_PROJECTID: "asco-app-2905"
  GCP_PUB_SUB_TOPICID: "projects/asco-app-2905/topics/publish-card-sync-meeting"
  GCP_PUB_SUB_SUBSCRIPTIONID: "pull-card-meeting"
