name: Deploy to App Engine

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: npm install  # Adjust based on your project's needs (npm, yarn, etc.)

      # Authenticate with Google Cloud (replace with your service account credentials)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

      # Deploy the application
      - name: Deploy to App Engine
        uses: marketplace/actions/deploy-gae-action@v1.0.1  # Replace with the latest version
        with:
          service-account: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}  # Base64 encoded service account JSON
          project-id: ${{ secrets.GCP_PROJECT_ID }}
          config-files: app.yaml  # Path to your App Engine configuration file
