name: Deploy to App Engine

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: npm install  # Adjust based on your project's needs (npm, yarn, etc.)

      # Authenticate with Google Cloud (replace with your service account credentials)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

      # Deploy the application
      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v2 # Replace with the latest version
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service: asco-app-2905 # Replace with your App Engine service name
          config: app.yaml # Path to your App Engine configuration file
